name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        uses: prezly/setup-github-actions@v1
        with:
          node: ${{ matrix.node-version }}
          pnpm: "8.11.0"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - run: pnpm build
